name: todotasks
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sticky_headers: ^0.3.0+2
  sqflite: ^2.0.2
  lottie: ^1.3.0
  flutter_local_notifications: ^9.4.0
  flutter_native_timezone: ^2.0.0
  flutter_bloc:
  path_provider: ^2.0.11
  date_picker_timeline: ^1.2.3
  flutter_staggered_animations: ^1.0.0
  marquee: ^2.2.3
  conditional_builder_null_safety: ^0.0.6
  rxdart: ^0.27.5
  flutter_zoom_drawer: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
     - family: Oswald-Bold.ttf
       fonts:
         - asset: assets/fonts/Oswald-Bold.ttf
         - asset: assets/fonts/Oswald-ExtraLight.ttf
         - asset: assets/fonts/Oswald-Light.ttf
         - asset: assets/fonts/Oswald-Medium.ttf
         - asset: assets/fonts/Oswald-Regular.ttf
         - asset: assets/fonts/Oswald-SemiBold.ttf
        